fix: restore tag check

diff --git a/.github/workflows/platform-deployment.yaml b/.github/workflows/platform-deployment.yaml
--- a/.github/workflows/platform-deployment.yaml
+++ b/.github/workflows/platform-deployment.yaml
@@ -28,16 +28,14 @@ jobs:
         run: |
           set -euxo pipefail
 
-          exit 0
+          if [ ! "${{ inputs.environment }}" =~ *prod ]; then
+            exit 0
+          fi
 
-          # if [ ! "${{ inputs.environment }}" =~ *prod ]; then
-          #   exit 0
-          # fi
-          #
-          # if [ ! "${{ github.ref_type }}" = "tag" ]; then
-          #   echo >&2 "ERROR: deploy on prod environment must use a git tag"
-          #   exit 1
-          # fi
+          if [ ! "${{ github.ref_type }}" = "tag" ]; then
+            echo >&2 "ERROR: deploy on prod environment must use a git tag"
+            exit 1
+          fi
 
       - name: Set NORM_ENV in 'env' context
         id: norm_env
