fix check_prod_tag in workflow

diff --git a/.github/workflows/platform-deployment.yaml b/.github/workflows/platform-deployment.yaml
--- a/.github/workflows/platform-deployment.yaml
+++ b/.github/workflows/platform-deployment.yaml
@@ -20,12 +20,12 @@ jobs:
         run: |
           set -euxo pipefail
 
-          if [ ! "${{ inputs.environment }}" = "prod"]; then
+          if [ ! "${{ inputs.environment }}" = "prod" ]; then
             exit 0
           fi
 
           if [ ! "${{ github.ref_type }}" = "tag" ]; then
-            echo >2 "ERROR: deploy on prod environment must use a git tag"
+            echo >&2 "ERROR: deploy on prod environment must use a git tag"
             exit 1
           fi
 
